from StatsWithSahira.StatsWithSahira import Mean
from StatsWithSahira.StatsWithSahira import Median
from StatsWithSahira.StatsWithSahira import Mode
from StatsWithSahira.StatsWithSahira import StandardDeviation
from StatsWithSahira.StatsWithSahira import Skewness
from StatsWithSahira.StatsWithSahira import UnivariateRegression
from StatsWithSahira.StatsWithSahira import MultiVariateRegression
